import { Meteor } from 'meteor/meteor';
import { SurveyThemes } from './surveyThemes';

// Additional themes part 2 (themes 11-20)
const additionalThemesPart2 = [
  {
    name: 'Coral Reef',
    color: '#e11d48',
    description: 'Vibrant coral theme with ocean-inspired colors',
    primaryColor: '#e11d48',
    secondaryColor: '#fb7185',
    accentColor: '#fda4af',
    backgroundColor: '#fff1f2',
    textColor: '#881337',
    headingFont: 'Lora, serif',
    bodyFont: 'Work Sans, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'accent',
    templateType: 'vibrant',
    priority: 65,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1546026423-cc4642628d2b'
  },
  {
    name: 'Emerald City',
    color: '#059669',
    description: 'Rich emerald green theme with jewel tones',
    primaryColor: '#059669',
    secondaryColor: '#10b981',
    accentColor: '#34d399',
    backgroundColor: '#ecfdf5',
    textColor: '#064e3b',
    headingFont: 'Spectral, serif',
    bodyFont: 'Karla, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'elegant',
    priority: 64,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc'
  },
  {
    name: 'Desert Sand',
    color: '#92400e',
    description: 'Warm desert-inspired theme with sand and earth tones',
    primaryColor: '#92400e',
    secondaryColor: '#d97706',
    accentColor: '#fbbf24',
    backgroundColor: '#fef3c7',
    textColor: '#78350f',
    headingFont: 'Amatic SC, cursive',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'natural',
    priority: 63,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1473580044384-7ba9967e16a0'
  },
  {
    name: 'Arctic Blue',
    color: '#0c4a6e',
    description: 'Cool arctic blue theme with icy tones',
    primaryColor: '#0c4a6e',
    secondaryColor: '#0ea5e9',
    accentColor: '#7dd3fc',
    backgroundColor: '#f0f9ff',
    textColor: '#082f49',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'cool',
    priority: 62,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1534570122623-99e8378a9aa7'
  },
  {
    name: 'Rose Gold',
    color: '#be185d',
    description: 'Elegant rose gold theme with pink and gold accents',
    primaryColor: '#be185d',
    secondaryColor: '#ec4899',
    accentColor: '#f9a8d4',
    backgroundColor: '#fdf2f8',
    textColor: '#831843',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'luxury',
    priority: 61,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9'
  },
  {
    name: 'Slate Gray',
    color: '#334155',
    description: 'Professional slate gray theme with clean lines',
    primaryColor: '#334155',
    secondaryColor: '#64748b',
    accentColor: '#94a3b8',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    headingFont: 'IBM Plex Sans, sans-serif',
    bodyFont: 'IBM Plex Sans, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'corporate',
    priority: 60,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab'
  },
  {
    name: 'Autumn Harvest',
    color: '#b45309',
    description: 'Warm autumn theme with harvest colors',
    primaryColor: '#b45309',
    secondaryColor: '#d97706',
    accentColor: '#fbbf24',
    backgroundColor: '#fffbeb',
    textColor: '#78350f',
    headingFont: 'Merriweather, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'seasonal',
    priority: 59,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1506202687253-52e1b29d3527'
  },
  {
    name: 'Teal Tranquility',
    color: '#0f766e',
    description: 'Calming teal theme with tranquil colors',
    primaryColor: '#0f766e',
    secondaryColor: '#14b8a6',
    accentColor: '#5eead4',
    backgroundColor: '#f0fdfa',
    textColor: '#134e4a',
    headingFont: 'Quicksand, sans-serif',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'calm',
    priority: 58,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e'
  },
  {
    name: 'Berry Blast',
    color: '#9d174d',
    description: 'Rich berry-colored theme with deep purples and pinks',
    primaryColor: '#9d174d',
    secondaryColor: '#db2777',
    accentColor: '#f472b6',
    backgroundColor: '#fdf2f8',
    textColor: '#831843',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'vibrant',
    priority: 57,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1423483641154-5411ec9c0ddf'
  },
  {
    name: 'Coffee Brown',
    color: '#78350f',
    description: 'Rich coffee-inspired theme with warm browns',
    primaryColor: '#78350f',
    secondaryColor: '#b45309',
    accentColor: '#d97706',
    backgroundColor: '#fffbeb',
    textColor: '#451a03',
    headingFont: 'Bitter, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'warm',
    priority: 56,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085'
  }
];

// Export part 2 of the themes
export const additionalThemesPart2Export = additionalThemesPart2;
