import { Meteor } from 'meteor/meteor';
import { SurveyThemes } from './surveyThemes';

// Additional themes part 3 (themes 21-30)
const additionalThemesPart3 = [
  {
    name: 'Amethyst Purple',
    color: '#6b21a8',
    description: 'Rich amethyst purple theme with jewel tones',
    primaryColor: '#6b21a8',
    secondaryColor: '#9333ea',
    accentColor: '#c084fc',
    backgroundColor: '#faf5ff',
    textColor: '#581c87',
    headingFont: 'Cinzel, serif',
    bodyFont: 'Raleway, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'luxury',
    priority: 55,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031'
  },
  {
    name: 'Sunny Yellow',
    color: '#ca8a04',
    description: 'Bright and cheerful yellow theme',
    primaryColor: '#ca8a04',
    secondaryColor: '#eab308',
    accentColor: '#facc15',
    backgroundColor: '#fefce8',
    textColor: '#713f12',
    headingFont: 'Nunito, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'cheerful',
    priority: 54,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1530530824905-661c730f429e'
  },
  {
    name: 'Crimson Classic',
    color: '#991b1b',
    description: 'Classic crimson red theme with timeless appeal',
    primaryColor: '#991b1b',
    secondaryColor: '#dc2626',
    accentColor: '#f87171',
    backgroundColor: '#fef2f2',
    textColor: '#7f1d1d',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Source Serif Pro, serif',
    buttonStyle: 'minimal',
    questionStyle: 'card',
    headerStyle: 'solid',
    templateType: 'classic',
    priority: 53,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176'
  },
  {
    name: 'Aqua Fresh',
    color: '#0e7490',
    description: 'Refreshing aqua theme with water-inspired colors',
    primaryColor: '#0e7490',
    secondaryColor: '#06b6d4',
    accentColor: '#67e8f9',
    backgroundColor: '#ecfeff',
    textColor: '#164e63',
    headingFont: 'Ubuntu, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'flat',
    headerStyle: 'gradient',
    templateType: 'fresh',
    priority: 52,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513002749550-c59d786b8e6c'
  },
  {
    name: 'Olive Garden',
    color: '#4d7c0f',
    description: 'Earthy olive green theme with natural tones',
    primaryColor: '#4d7c0f',
    secondaryColor: '#65a30d',
    accentColor: '#a3e635',
    backgroundColor: '#f7fee7',
    textColor: '#3f6212',
    headingFont: 'Bitter, serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'natural',
    priority: 51,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6'
  },
  {
    name: 'Pastel Dream',
    color: '#db2777',
    description: 'Soft pastel theme with dreamy colors',
    primaryColor: '#db2777',
    secondaryColor: '#ec4899',
    accentColor: '#fbcfe8',
    backgroundColor: '#fdf2f8',
    textColor: '#831843',
    headingFont: 'Dancing Script, cursive',
    bodyFont: 'Quicksand, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'playful',
    priority: 50,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43'
  },
  {
    name: 'Indigo Night',
    color: '#3730a3',
    description: 'Deep indigo theme with night sky inspiration',
    primaryColor: '#3730a3',
    secondaryColor: '#4f46e5',
    accentColor: '#818cf8',
    backgroundColor: '#eef2ff',
    textColor: '#312e81',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Inter, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'flat',
    headerStyle: 'gradient',
    templateType: 'dark',
    priority: 49,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401'
  },
  {
    name: 'Terracotta',
    color: '#c2410c',
    description: 'Warm terracotta theme with earthy tones',
    primaryColor: '#c2410c',
    secondaryColor: '#ea580c',
    accentColor: '#fb923c',
    backgroundColor: '#fff7ed',
    textColor: '#7c2d12',
    headingFont: 'Arvo, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'earthy',
    priority: 48,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1508615070457-7baeba4003ab'
  },
  {
    name: 'Turquoise Breeze',
    color: '#0d9488',
    description: 'Refreshing turquoise theme with breezy feel',
    primaryColor: '#0d9488',
    secondaryColor: '#14b8a6',
    accentColor: '#5eead4',
    backgroundColor: '#f0fdfa',
    textColor: '#115e59',
    headingFont: 'Quicksand, sans-serif',
    bodyFont: 'Work Sans, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'fresh',
    priority: 47,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e'
  },
  {
    name: 'Burgundy Classic',
    color: '#881337',
    description: 'Rich burgundy theme with classic elegance',
    primaryColor: '#881337',
    secondaryColor: '#be123c',
    accentColor: '#fb7185',
    backgroundColor: '#fff1f2',
    textColor: '#4c0519',
    headingFont: 'Libre Baskerville, serif',
    bodyFont: 'Lora, serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'solid',
    templateType: 'classic',
    priority: 46,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d'
  }
];

// Export part 3 of the themes
export const additionalThemesPart3Export = additionalThemesPart3;
