import { Meteor } from 'meteor/meteor';
import { SurveyThemes } from './surveyThemes';

// Additional themes part 5 (themes 41-50)
const additionalThemesPart5 = [
  {
    name: 'Charcoal Modern',
    color: '#1f2937',
    description: 'Modern charcoal theme with sleek design',
    primaryColor: '#1f2937',
    secondaryColor: '#374151',
    accentColor: '#6b7280',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    headingFont: 'IBM Plex Sans, sans-serif',
    bodyFont: 'IBM Plex Sans, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'modern',
    priority: 35,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1470790376778-a9fbc86d70e2'
  },
  {
    name: 'Tangerine Dream',
    color: '#ea580c',
    description: 'Vibrant tangerine orange theme with energy',
    primaryColor: '#ea580c',
    secondaryColor: '#f97316',
    accentColor: '#fb923c',
    backgroundColor: '#fff7ed',
    textColor: '#9a3412',
    headingFont: 'Nunito, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'energetic',
    priority: 34,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869'
  },
  {
    name: 'Sapphire Blue',
    color: '#1e40af',
    description: 'Deep sapphire blue theme with jewel tones',
    primaryColor: '#1e40af',
    secondaryColor: '#3b82f6',
    accentColor: '#60a5fa',
    backgroundColor: '#eff6ff',
    textColor: '#1e3a8a',
    headingFont: 'Raleway, sans-serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'professional',
    priority: 33,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809'
  },
  {
    name: 'Moss Green',
    color: '#3f6212',
    description: 'Natural moss green theme with earthy appeal',
    primaryColor: '#3f6212',
    secondaryColor: '#65a30d',
    accentColor: '#a3e635',
    backgroundColor: '#f7fee7',
    textColor: '#365314',
    headingFont: 'Bitter, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'natural',
    priority: 32,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6'
  },
  {
    name: 'Lilac Breeze',
    color: '#8b5cf6',
    description: 'Soft lilac theme with gentle appeal',
    primaryColor: '#8b5cf6',
    secondaryColor: '#a78bfa',
    accentColor: '#c4b5fd',
    backgroundColor: '#f5f3ff',
    textColor: '#5b21b6',
    headingFont: 'Quicksand, sans-serif',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'gentle',
    priority: 31,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1464618663641-bbdd760ae84a'
  },
  {
    name: 'Rustic Brown',
    color: '#78350f',
    description: 'Warm rustic brown theme with natural appeal',
    primaryColor: '#78350f',
    secondaryColor: '#92400e',
    accentColor: '#b45309',
    backgroundColor: '#fffbeb',
    textColor: '#451a03',
    headingFont: 'Arvo, serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'rustic',
    priority: 30,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1508615070457-7baeba4003ab'
  },
  {
    name: 'Cyan Cool',
    color: '#0891b2',
    description: 'Cool cyan theme with refreshing feel',
    primaryColor: '#0891b2',
    secondaryColor: '#06b6d4',
    accentColor: '#22d3ee',
    backgroundColor: '#ecfeff',
    textColor: '#155e75',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'flat',
    headerStyle: 'gradient',
    templateType: 'cool',
    priority: 29,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513002749550-c59d786b8e6c'
  },
  {
    name: 'Magenta Magic',
    color: '#a21caf',
    description: 'Vibrant magenta theme with magical appeal',
    primaryColor: '#a21caf',
    secondaryColor: '#c026d3',
    accentColor: '#e879f9',
    backgroundColor: '#fdf4ff',
    textColor: '#701a75',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'vibrant',
    priority: 28,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031'
  },
  {
    name: 'Slate Professional',
    color: '#334155',
    description: 'Professional slate gray theme for business',
    primaryColor: '#334155',
    secondaryColor: '#475569',
    accentColor: '#64748b',
    backgroundColor: '#f8fafc',
    textColor: '#0f172a',
    headingFont: 'IBM Plex Sans, sans-serif',
    bodyFont: 'IBM Plex Sans, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'corporate',
    priority: 27,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab'
  },
  {
    name: 'Amber Glow',
    color: '#d97706',
    description: 'Warm amber theme with golden glow',
    primaryColor: '#d97706',
    secondaryColor: '#f59e0b',
    accentColor: '#fbbf24',
    backgroundColor: '#fffbeb',
    textColor: '#92400e',
    headingFont: 'Merriweather, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'warm',
    priority: 26,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869'
  }
];

// Export part 5 of the themes
export const additionalThemesPart5Export = additionalThemesPart5;
