import { Meteor } from 'meteor/meteor';
import { SurveyThemes } from './surveyThemes';

// Additional 50 themes to provide a rich variety of options
const additionalThemes = [
  {
    name: 'Ocean Blue',
    color: '#1e3a8a',
    description: 'Deep blue theme inspired by the ocean depths',
    primaryColor: '#1e3a8a',
    secondaryColor: '#3b82f6',
    accentColor: '#38bdf8',
    backgroundColor: '#f0f9ff',
    textColor: '#0f172a',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Inter, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'modern',
    priority: 75,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e'
  },
  {
    name: 'Forest Green',
    color: '#166534',
    description: 'Earthy green theme inspired by lush forests',
    primaryColor: '#166534',
    secondaryColor: '#22c55e',
    accentColor: '#4ade80',
    backgroundColor: '#f0fdf4',
    textColor: '#14532d',
    headingFont: 'Bitter, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'nature',
    priority: 74,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1448375240586-882707db888b'
  },
  {
    name: 'Sunset Orange',
    color: '#c2410c',
    description: 'Warm sunset-inspired theme with orange and red tones',
    primaryColor: '#c2410c',
    secondaryColor: '#f97316',
    accentColor: '#fb923c',
    backgroundColor: '#fff7ed',
    textColor: '#431407',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'warm',
    priority: 73,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869'
  },
  {
    name: 'Lavender Dreams',
    color: '#7e22ce',
    description: 'Soothing lavender theme with purple accents',
    primaryColor: '#7e22ce',
    secondaryColor: '#a855f7',
    accentColor: '#c084fc',
    backgroundColor: '#faf5ff',
    textColor: '#581c87',
    headingFont: 'Quicksand, sans-serif',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'elegant',
    priority: 72,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1464618663641-bbdd760ae84a'
  },
  {
    name: 'Charcoal Elegance',
    color: '#1f2937',
    description: 'Sophisticated dark theme with charcoal and gray tones',
    primaryColor: '#1f2937',
    secondaryColor: '#4b5563',
    accentColor: '#6b7280',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    headingFont: 'Raleway, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'professional',
    priority: 71,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1470790376778-a9fbc86d70e2'
  },
  {
    name: 'Ruby Red',
    color: '#b91c1c',
    description: 'Bold and vibrant ruby red theme',
    primaryColor: '#b91c1c',
    secondaryColor: '#ef4444',
    accentColor: '#f87171',
    backgroundColor: '#fef2f2',
    textColor: '#7f1d1d',
    headingFont: 'Oswald, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'solid',
    templateType: 'bold',
    priority: 70,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176'
  },
  {
    name: 'Mint Fresh',
    color: '#047857',
    description: 'Refreshing mint green theme with cool tones',
    primaryColor: '#047857',
    secondaryColor: '#10b981',
    accentColor: '#34d399',
    backgroundColor: '#ecfdf5',
    textColor: '#064e3b',
    headingFont: 'Ubuntu, sans-serif',
    bodyFont: 'Nunito Sans, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'bordered',
    headerStyle: 'accent',
    templateType: 'fresh',
    priority: 69,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e'
  },
  {
    name: 'Golden Sunset',
    color: '#b45309',
    description: 'Rich golden theme inspired by sunset hues',
    primaryColor: '#b45309',
    secondaryColor: '#f59e0b',
    accentColor: '#fbbf24',
    backgroundColor: '#fffbeb',
    textColor: '#78350f',
    headingFont: 'Merriweather, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'warm',
    priority: 68,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869'
  },
  {
    name: 'Sky Blue',
    color: '#0369a1',
    description: 'Light and airy sky blue theme',
    primaryColor: '#0369a1',
    secondaryColor: '#0ea5e9',
    accentColor: '#38bdf8',
    backgroundColor: '#f0f9ff',
    textColor: '#075985',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'light',
    priority: 67,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513002749550-c59d786b8e6c'
  },
  {
    name: 'Midnight Purple',
    color: '#4c1d95',
    description: 'Deep purple theme with midnight tones',
    primaryColor: '#4c1d95',
    secondaryColor: '#7c3aed',
    accentColor: '#a78bfa',
    backgroundColor: '#f5f3ff',
    textColor: '#2e1065',
    headingFont: 'Poppins, sans-serif',
    bodyFont: 'Inter, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'dark',
    priority: 66,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401'
  }
];

// Export part 1 of the themes
export const additionalThemesPart1 = additionalThemes;
