import { Meteor } from 'meteor/meteor';
import { SurveyThemes } from './surveyThemes';

// Additional themes part 4 (themes 31-40)
const additionalThemesPart4 = [
  {
    name: 'Sage Wisdom',
    color: '#4d7c0f',
    description: 'Calming sage green theme with natural appeal',
    primaryColor: '#4d7c0f',
    secondaryColor: '#65a30d',
    accentColor: '#a3e635',
    backgroundColor: '#f7fee7',
    textColor: '#365314',
    headingFont: 'Merriweather, serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'bordered',
    headerStyle: 'solid',
    templateType: 'natural',
    priority: 45,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6'
  },
  {
    name: 'Electric Blue',
    color: '#1d4ed8',
    description: 'Vibrant electric blue theme with energy',
    primaryColor: '#1d4ed8',
    secondaryColor: '#3b82f6',
    accentColor: '#60a5fa',
    backgroundColor: '#eff6ff',
    textColor: '#1e3a8a',
    headingFont: 'Exo, sans-serif',
    bodyFont: 'Roboto, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'modern',
    priority: 44,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809'
  },
  {
    name: 'Chocolate Delight',
    color: '#78350f',
    description: 'Rich chocolate brown theme with warm tones',
    primaryColor: '#78350f',
    secondaryColor: '#92400e',
    accentColor: '#d97706',
    backgroundColor: '#fffbeb',
    textColor: '#451a03',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'warm',
    priority: 43,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1511381939415-e44015466834'
  },
  {
    name: 'Fuchsia Fun',
    color: '#c026d3',
    description: 'Playful fuchsia theme with vibrant energy',
    primaryColor: '#c026d3',
    secondaryColor: '#d946ef',
    accentColor: '#e879f9',
    backgroundColor: '#fdf4ff',
    textColor: '#86198f',
    headingFont: 'Pacifico, cursive',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'playful',
    priority: 42,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1517999144091-3d9dca6d1e43'
  },
  {
    name: 'Stormy Gray',
    color: '#374151',
    description: 'Sophisticated stormy gray theme with depth',
    primaryColor: '#374151',
    secondaryColor: '#4b5563',
    accentColor: '#9ca3af',
    backgroundColor: '#f9fafb',
    textColor: '#111827',
    headingFont: 'Raleway, sans-serif',
    bodyFont: 'Source Sans Pro, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'flat',
    headerStyle: 'solid',
    templateType: 'professional',
    priority: 41,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1485470733090-0aae1788d5af'
  },
  {
    name: 'Lime Fresh',
    color: '#65a30d',
    description: 'Energetic lime green theme with fresh appeal',
    primaryColor: '#65a30d',
    secondaryColor: '#84cc16',
    accentColor: '#a3e635',
    backgroundColor: '#f7fee7',
    textColor: '#3f6212',
    headingFont: 'Ubuntu, sans-serif',
    bodyFont: 'Open Sans, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'bordered',
    headerStyle: 'accent',
    templateType: 'energetic',
    priority: 40,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1497250681960-ef046c08a56e'
  },
  {
    name: 'Royal Blue',
    color: '#1e40af',
    description: 'Regal royal blue theme with classic appeal',
    primaryColor: '#1e40af',
    secondaryColor: '#3b82f6',
    accentColor: '#93c5fd',
    backgroundColor: '#eff6ff',
    textColor: '#1e3a8a',
    headingFont: 'Cinzel, serif',
    bodyFont: 'Raleway, sans-serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'gradient',
    templateType: 'classic',
    priority: 39,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809'
  },
  {
    name: 'Peach Perfect',
    color: '#ea580c',
    description: 'Warm peach theme with soft tones',
    primaryColor: '#ea580c',
    secondaryColor: '#f97316',
    accentColor: '#fb923c',
    backgroundColor: '#fff7ed',
    textColor: '#9a3412',
    headingFont: 'Quicksand, sans-serif',
    bodyFont: 'Nunito, sans-serif',
    buttonStyle: 'rounded',
    questionStyle: 'card',
    headerStyle: 'solid',
    templateType: 'warm',
    priority: 38,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1495616811223-4d98c6e9c869'
  },
  {
    name: 'Deep Sea',
    color: '#0f766e',
    description: 'Deep teal theme inspired by ocean depths',
    primaryColor: '#0f766e',
    secondaryColor: '#14b8a6',
    accentColor: '#2dd4bf',
    backgroundColor: '#f0fdfa',
    textColor: '#134e4a',
    headingFont: 'Montserrat, sans-serif',
    bodyFont: 'Lato, sans-serif',
    buttonStyle: 'minimal',
    questionStyle: 'bordered',
    headerStyle: 'gradient',
    templateType: 'cool',
    priority: 37,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1513002749550-c59d786b8e6c'
  },
  {
    name: 'Plum Elegance',
    color: '#7e22ce',
    description: 'Rich plum theme with elegant appeal',
    primaryColor: '#7e22ce',
    secondaryColor: '#a855f7',
    accentColor: '#c084fc',
    backgroundColor: '#faf5ff',
    textColor: '#581c87',
    headingFont: 'Playfair Display, serif',
    bodyFont: 'Source Serif Pro, serif',
    buttonStyle: 'pill',
    questionStyle: 'card',
    headerStyle: 'accent',
    templateType: 'elegant',
    priority: 36,
    isActive: true,
    previewImageUrl: 'https://images.unsplash.com/photo-1550684376-efcbd6e3f031'
  }
];

// Export part 4 of the themes
export const additionalThemesPart4Export = additionalThemesPart4;
